# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "fredrikbaberg/ros-kinetic-base"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "public_network"
  config.vm.hostname = "simulation"

  config.vm.provider "hyperv" do |hv|
    hv.memory = "2048"
    hv.cpus = "2"
    hv.vmname = "sim"
    hv.enable_virtualization_extensions = true
    hv.linked_clone = true
    hv.vm_integration_services = {
      guest_service_interface: true,
      heartbeat: true,
      key_value_pair_exchange: true,
      shutdown: true,
      time_synchronization: true,
      vss: true
    }
  end

  config.vm.provision "provision", type: "shell", path: "provision_sim.sh", privileged: false
end
