# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "lipro/ubuntu-14.04"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "public_network"
  config.vm.hostname = "ros-indigo"

  config.vm.provider "hyperv" do |hv|
    hv.memory = "2048"
    hv.cpus = "2"
    hv.vmname = "ros-indigo"
    hv.enable_virtualization_extensions = true
    hv.linked_clone = false
    hv.vm_integration_services = {
      guest_service_interface: true,
      heartbeat: true,
      key_value_pair_exchange: true,
      shutdown: true,
      time_synchronization: true,
      vss: true
    }
  end
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = "2"
  end
  config.vm.provision "provision", type: "shell", path: "provision.sh", privileged: true
end
